language: python
before_install:
- pip install pycodestyle
- pip install pytest
- pip install pytest-cov
- pip install coveralls
- pip install sphinx
- pip install sphinx_rtd_theme
- pip install tpDcc-core
- pip install tpDcc-libs-unittests
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --exclude */resources/res.py --max-line-length=120
  --ignore=E402 {} +
- pytest --cov=tpDcc
- sphinx-apidoc -f -e -o docs/sphinx tpDcc
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: pIHwiW8J3jx34tzHpJoidth4vyWdeYGNCip+EqpD0mexHRqrvXek5geary5G0guOxCqn2yPr475Lacn1SPN1XJKuE+UrZyqKuRsDozJ/HKA+YKt+5it4ImJdV0YR2qxtP73FBvwbwHTympMG1e9zWp6gtheDU0/GAZS0RxcGj5SaLjNTIYd6F6kpiXwXfD6T7ViDTR3y358n6PzEn0tyZQo28/ObuODaV+CC50PoO5QLj5EinTj5UyJ8w1GNLGhx01ICj7l7Z0yMiP/+FkE7fpEa6lJJ7+0SVINQIIP4rfQCfaThFUKt8fry977O16M3x0BAdox+2NFsdTAzc6ith6/w4PisejtfKJ3+zUQ97OCCczI5ucgnhN64CU0q4HVoKhYA2yANocO2v+FMLxoRTLDDMaGxoodfy3EPuGSZ5jzajUcRExtt+vWciBPKpiENM/CenUbM+UEyEzYudyu1U4AxtaXjMDcm4S6g9WBqbmNQ7SfHgTS/65AKiaxMYnX8MST+jAJ3iKHm59tYgONrO3jBdxck/xgdROFI6LwFSaw6Dra/eom/stYveAWiakMUVsLefGd9ta/pqJ9lsly6wtT0WWCdbfV7j9rKcmbReTyCfbgo/uA1HilumMsjmHHAum3my8S77fDuWrvUco5w+3TZj7lGzz0xmufiSa0T57k=
    on:
      branch: master
      tags: true
