language: python
services:
  docker
python:
  - "3.7"

jobs:
  include:
    - stage: style
      name: "Code Style (PEP8)"
      before_install:
        - pip install pycodestyle
      script:
        - find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
    - stage: standalone
      name: "Unit Tests (standalone)"
      before_install:
        - pip install pytest
        - pip install pytest-cov
        - pip install coveralls
      install:
        - python setup.py install
      script:
        - pytest --cov=tpDcc
      after_success:
        - coveralls
    - stage: maya2019
      name: "Unit Tests (Maya 2019)"
      before_install:
        - docker pull mottosso/maya:2019
        - docker run mottosso/maya:2019
        - dock run /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests -v
    - stage: docs
      name: "Build Documentation"
      before_install:
        - pip install sphinx
        - pip install sphinx_rtd_theme
      script:
        - sphinx-apidoc -f -e -o docs/sphinx tpDcc
        - sphinx-build -M html ./docs/sphinx ./
      after_success:
        - cd html && touch .nojekyll && cd ../
    - stage: deploy
      name: "Deploy"
      deploy:
        - provider: pages
          cleanup: false
          github_token: "$GITHUB_TOKEN"
          keep_history: true
          local_dir: html
          on:
            branch: master
        - provider: pypi
          cleanup: false
          user: tpoveda
          password:
            secure: FVSPTXZles34oDK4KqM18/59B9vfjD4FeiKjMQSNlTLzxQDXvat0tcquWNQi/RBtr8aq8EsHG/DiuSfKCxnY3hviwbvTV44S1CXwzEB5TN8h9K1L0FWivwpeIO6bQvdL+iKKXBYbfhigzC/DKobBTLS2upewExUCgPBAMXcQAsebOAJIqCaJYDSMU1X/+E2udjlEwP+IVydVTSy+EL0U0OAHI+Rfnld37rbrPTPGxmhq4QbSxMhQqeLEsBibnP1itCiG6KSpY9t8aJqbva4vxqIA5k70WiTOxHwbKTcSTwNtsUAQ6oAg38iFEtYziCZMFBS47FT2Z4C8C2tNQK6bI3HU4so8zUBds9cAf+ItjHx6a2iHr38EsckAi3EJJCLxL7hg0hczo9utJyFn8Vb7/cdYk6icR/qOg0Y6Mmi45GGwYjhJ9tkPrsdmcdZk/y76HYrZiSU+J8SzXoerkg2XwgYwwGJBvZjl2bpdJLRIGY2N69x7HSA1NJzDvnlG2+i1rxWVyUz4y62fJSi/uIM819iMSW6Q/L+HC3r019JReRVz79pim+VnKm78VbmaxDqYl1PtzXlr7L/OrrYGTile5XQVWmjVoTCoirKg+Y3j2plYP5Uvzjz2v92B7IErIqVd+zWuiPe+rMc67qx3KKKgy6SPXBrF8KZPRuUf7Fxo8+I=
          on:
            branch: master
            tags: true