language: python
before_install:
- pip install pycodestyle
- pip install pytest
- pip install pytest-cov
- pip install coveralls
- pip install sphinx
- pip install sphinx_rtd_theme
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --exclude */externals/* --max-line-length=120
  --ignore=E402 {} +
- pytest --cov=tpDcc
- sphinx-apidoc -f -e -o docs/sphinx tpDcc
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: 1BMYUU9O4wOFcUEp/1NWaPEv8IJr/kDBuGED+P5SZNw/YifgL5Ks5HzV/YCCm+UJC4GviNFg6ZKPX02L7VImy2HK6sTh3luHB0e9u4r0+zQJyZG14xawDZByYaPalWYxzFiBDVETGz9CnuD/6SINSG4LfRWqffiEZmYpPrrX1LA9aNLE03NnrYzMZuO4JIHyoCMvm/9YYzMcO+LPermrcLOlEdW9blm/ZlwQh73vV9GonOnLXjTReAd6DVKvd0jJsL3L5Oh8gQFCla5CQ9AcKiU5Fr8h8b4K+Wt3ot15EBIeRN0t27ckN/RMwx9EFBncGZOtjOL8mAzgqkKWqxtGTFA1CibI88fb0QotbzrSwRoaqbtmy32t4VHhScuUbV33bdMgSyERyEg/QsPgq5rmU7NM0ou2KX4yGFuCE5l5NZqLVUJn+AIY0yavn8zLpRbRsT4A6H4lXxd7NNdHQUBE3oheJ1x9xx0pY7t5HJxWVFBe3jWJnCWkqSEz/v5bqA++BFlRBS/F2F+8S4leQ0L+0JtMtlfny1wn3PL54PyQfszJrhkPQ18tgd7sTFiJrg1BDlBkRW/T64kbJ5T11bvtVHAhuxaITCkMKzVbtrwogGIQ5SL269oE1j3wxa8v4gHaoB9M12LTEejDoQDXfQla/vYr8Rm/cFHdJ++yshhty2I=
    on:
      branch: master
      tags: true