# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [ push, pull_request ]

jobs:

  standalone:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [2.7, 3.7]
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle
      - name: Code Style (PEP8)
        run: |
           find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
      - name: Build Documentation
        run: |
          sphinx-apidoc -f -e -o docs/sphinx tpDcc
          sphinx-build -M html ./docs/sphinx ./
          cd html && touch .nojekyll && cd ../

  maya2019:
    needs: standalone
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run Unit Tests
      uses: docker://mottosso/maya:2019
      with:
        args: /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests -v

  maya2020:
    needs: standalone
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run Unit Tests
        uses: docker://mottosso/maya:2020
        with:
          args: /usr/autodesk/maya/bin/mayapy -m unittest discover -s ./tests -v